# Generated by Django 3.1.5 on 2021-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
